### ISSUE TITLE
Lookup and upload issue

### ISSUE THREAD

**Issue by Murtuza321** [cweems/twilio-bulk-lookup#11]
Unable to lookup or upload contact gating this error 

We're sorry, but something went wrong.

If you are the application owner check the logs for more information.

**Comment by Murtuza321** [comment]
2020-01-15T14:08:35.589739+00:00 heroku[router]: at=info method=GET path="/lookup" host=murtazaapp.herokuapp.com request_id=f56f58e3-86b3-4256-bce1-96eccf982a3e fwd="198.98.54.241" dyno=web.1 connect=1ms service=25ms status=500 bytes=1827 protocol=https

2020-01-15T14:08:35.570789+00:00 app[web.1]: I, [2020-01-15T14:08:35.570639 #4]  INFO -- : [f56f58e3-86b3-4256-bce1-96eccf982a3e] Started GET "/lookup" for 198.98.54.241 at 2020-01-15 14:08:35 +0000

2020-01-15T14:08:35.572047+00:00 app[web.1]: I, [2020-01-15T14:08:35.571924 #4]  INFO -- : [f56f58e3-86b3-4256-bce1-96eccf982a3e] Processing by LookupController#run as HTML

2020-01-15T14:08:35.579842+00:00 app[web.1]: D, [2020-01-15T14:08:35.579685 #4] DEBUG -- : [f56f58e3-86b3-4256-bce1-96eccf982a3e]   [1m[36mContact Load (4.0ms)[0m  [1m[34mSELECT  "contacts".* FROM "contacts" ORDER BY "contacts"."id" ASC LIMIT $1[0m  [["LIMIT", 1000]]

2020-01-15T14:08:35.583175+00:00 app[web.1]: I, [2020-01-15T14:08:35.583039 #4]  INFO -- : [f56f58e3-86b3-4256-bce1-96eccf982a3e] Completed 500 Internal Server Error in 11ms (ActiveRecord: 4.0ms)

2020-01-15T14:08:35.589538+00:00 app[web.1]: F, [2020-01-15T14:08:35.589173 #4] FATAL -- : [f56f58e3-86b3-4256-bce1-96eccf982a3e]   

2020-01-15T14:08:35.591881+00:00 app[web.1]: F, [2020-01-15T14:08:35.591737 #4] FATAL -- : [f56f58e3-86b3-4256-bce1-96eccf982a3e] Redis::CannotConnectError (Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)):

2020-01-15T14:08:35.592000+00:00 app[web.1]: F, [2020-01-15T14:08:35.591918 #4] FATAL -- : [f56f58e3-86b3-4256-bce1-96eccf982a3e]   

2020-01-15T14:08:35.592133+00:00 app[web.1]: F, [2020-01-15T14:08:35.592049 #4] FATAL -- : [f56f58e3-86b3-4256-bce1-96eccf982a3e] app/controllers/lookup_controller.rb:6:in `block in run'

2020-01-15T14:08:35.592136+00:00 app[web.1]: [f56f58e3-86b3-4256-bce1-96eccf982a3e] app/controllers/lookup_controller.rb:5:in `run'

**Comment by bitlayergit** [comment]
I had this error, was able to fix it by putting the rails API

**Comment by bitlayergit** [comment]
but still cant lookup anything, I upload the csv file and get no results; probably something between twilio and the tool, trying to contact the developer in linkedin to work together in the fix

**Comment by mleefiend** [comment]
Any update on this @bitlayergit ?  Were you able to get ahold of @cweems ?

What should the format of the CSV file look like?

**Comment by cweems** [comment]
I believe this error means that you aren't able to connect to Redis. Redis setup was missing from the README so I've added those steps now: https://github.com/cweems/twilio-bulk-lookup/blob/master/README.md

**Comment by mleefiend** [comment]
Thanks @cweems that worked!  What should the format of the CSV file be?  I've created a test csv file with two numbers separated by comma but the system is now giving an error of:

Error: can't write unknown attribute `_formatted_phone_number`

**Comment by jason200434** [comment]
> I believe this error means that you aren't able to connect to Redis. Redis setup was missing from the README so I've added those steps now: https://github.com/cweems/twilio-bulk-lookup/blob/master/README.md

Can you please upgrade the version of ruby???
